/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import javax.swing.table.DefaultTableModel;
import my_package.ButtonEditor;
import my_package.ButtonRenderer;
import java.sql.*; 
import net.proteanit.sql.DbUtils; 
import javax.swing.JOptionPane; 
import Admin.AdminProfile;


/**
 *
 * @author pc
 */
public class admindash extends javax.swing.JFrame {
    String loggedInUser;
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;

    /**
     * Creates new form admindash
     */
    public admindash(String user) {
        new my_config.config().checkSession(this);
        if (!this.isDisplayable()) {
        return; // Hunongon ang constructor dinhi kon wala naka-login
    }
        initComponents();
    this.loggedInUser = user;
    refreshTable();
    displayProducts();
    }
    public void displayProducts() {
    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:project.db");
        String sql = "SELECT p_id AS ID, p_name AS 'Product Name', p_category AS Category, p_price AS Price FROM products";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();
        
        // Gamit ang rs2xml.jar
        productTable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        
        conn.close();
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}

    admindash() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   public void refreshTable() {
    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:project.db");
        String sql = "SELECT p_id as 'ID', p_name as 'Product Name', p_category as 'Category', p_price as 'Price' FROM products";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        // 1. I-load ang database data (Kini ang mo-reset sa table)
        productTable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

        // 2. I-add pag-usab ang columns para sa buttons
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        model.addColumn("Update");
        model.addColumn("Delete");

        // 3. I-BUTANG PAG-USAB ANG TEXT SA MATAG ROW (Importante!)
        for (int i = 0; i < productTable.getRowCount(); i++) {
            productTable.setValueAt("Update", i, 4); // Column index 4
            productTable.setValueAt("Delete", i, 5); // Column index 5
        }

        // 4. I-reapply ang Renderers ug Editors
        productTable.getColumn("Update").setCellRenderer(new my_package.ButtonRenderer("Update"));
        productTable.getColumn("Delete").setCellRenderer(new my_package.ButtonRenderer("Delete"));
        productTable.getColumn("Update").setCellEditor(new my_package.ButtonEditor(productTable, "Update"));
        productTable.getColumn("Delete").setCellEditor(new my_package.ButtonEditor(productTable, "Delete"));

        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddProduct = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        viewusers = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 0, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("RAY'S FAST FOOD");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 50));

        jPanel2.setBackground(new java.awt.Color(249, 231, 159));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Dashboard");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Products");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Staff Accounts");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Orders");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Sales Reports");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, -1));

        lbl_logout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_logout.setText("Logout");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Admin Profile");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 130, 420));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 0, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("ADMIN PANEL");
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Manage Products");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        AddProduct.setEditable(false);
        AddProduct.setBackground(new java.awt.Color(255, 153, 0));
        AddProduct.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        AddProduct.setForeground(new java.awt.Color(255, 255, 255));
        AddProduct.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AddProduct.setText("Add Product");
        AddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductMouseClicked(evt);
            }
        });
        AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductActionPerformed(evt);
            }
        });
        jPanel3.add(AddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 30));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 153, 0));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Manage Categories");
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, 30));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 153, 0));
        jTextField5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("View Sales Reports");
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 120, 30));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 153, 0));
        jTextField6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("View Orders");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 110, 30));

        viewusers.setEditable(false);
        viewusers.setBackground(new java.awt.Color(255, 153, 0));
        viewusers.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewusers.setForeground(new java.awt.Color(255, 255, 255));
        viewusers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        viewusers.setText("View Users");
        viewusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewusersMouseClicked(evt);
            }
        });
        viewusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewusersActionPerformed(evt);
            }
        });
        jPanel3.add(viewusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 110, 30));

        productTable.setBackground(new java.awt.Color(204, 204, 204));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        productTable.setRowHeight(40);
        jScrollPane1.setViewportView(productTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 600, 230));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 770, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 930, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewusersMouseClicked
                                              
    // Siguraduha nga gamay tanan ang letra sa "viewusers" 
    // base sa imong file name sa Projects tab
    viewusers vu = new viewusers(); 
    vu.setVisible(true); // I-pakita ang pikas frame
    this.dispose();      // I-close ang Admin Panel

    }//GEN-LAST:event_viewusersMouseClicked

    private void AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductActionPerformed
  
    }//GEN-LAST:event_AddProductActionPerformed

    private void viewusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewusersActionPerformed
  
    }//GEN-LAST:event_viewusersActionPerformed

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        // 1. Confirmation Dialog
    int a = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
    
    if (a == JOptionPane.YES_OPTION) { // Mas safe gamiton ang YES_OPTION kaysa manual nga '0'
        // 2. Paghimo og instance sa Login frame
        // Siguraduha nga ang spelling ni-match sa imong Login file
        my_package.Login loginFrame = new my_package.Login(); 
        
        // 3. I-pakita ang login screen
        loginFrame.setVisible(true); 
        
        // 4. I-close ang karaan nga dashboard
        this.dispose(); 
    }
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        AdminProfile profile = new AdminProfile(loggedInUser);
    profile.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void AddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductMouseClicked
        // 1. Paghimo og instance sa imong JDialog
    // Siguruha nga "addproduct" ang saktong spelling sa imong JDialog class
    addproduct add = new addproduct(this, true); 
    
    // 2. I-center ang dialog sa tunga sa dashboard
    add.setLocationRelativeTo(this);
    
    // 3. I-pakita ang dialog
    add.setVisible(true);
    
    // 4. Human og close sa dialog, i-refresh ang table para makita ang bag-ong data
    refreshTable(); 

    }//GEN-LAST:event_AddProductMouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // I-refresh ang data inig abli
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        vieworders vo = new vieworders();
        vo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jTextField6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindash("admin").setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField viewusers;
    // End of variables declaration//GEN-END:variables
}
