/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import javax.swing.table.DefaultTableModel;
import my_package.ButtonEditor;
import my_package.ButtonRenderer;
import java.sql.*; 
import net.proteanit.sql.DbUtils; 
import javax.swing.JOptionPane; 
import Admin.AdminProfile;
import Admin.addproduct;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import java.awt.AlphaComposite;
import java.awt.Image;
import java.awt.RenderingHints;


/**
 *
 * @author pc
 */
public class admindash extends javax.swing.JFrame {
    String loggedInUser;
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;

    /**
     * Creates new form admindash
     */
    public admindash(String user) {
        new my_config.config().checkSession(this);
        if (!this.isDisplayable()) {
        return; // Hunongon ang constructor dinhi kon wala naka-login
    }
        initComponents();
       
        this.loggedInUser = user;
   
    
    refreshTable();
    
    }


    public void displayProducts() {
    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:project.db");
        String sql = "SELECT p_id AS ID, p_name AS 'Product Name', p_category AS Category, p_price AS Price FROM products";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();
        
        // Gamit ang rs2xml.jar
        productTable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        
        conn.close();
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}

    admindash() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   public void refreshTable() {
   try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:project.db");
        // SELECT query para sa imong mga produkto
        String sql = "SELECT p_id as 'ID', p_name as 'Product Name', p_category as 'Category', p_price as 'Price' FROM products";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        // 1. I-load ang database data sa table
        productTable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

        // 2. I-add ang dugang nga columns para sa buttons
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        model.addColumn("Update");
        model.addColumn("Delete");

        // 3. I-butang ang text nga "Update" ug "Delete" sa matag row
        for (int i = 0; i < productTable.getRowCount(); i++) {
    productTable.setValueAt("Update", i, 4); 
    productTable.setValueAt("Delete", i, 5); 
}

        // 4. I-reapply ang Renderers ug Editors para mahimong clickable buttons
        productTable.getColumn("Update").setCellRenderer(new my_package.ButtonRenderer("Update"));
        productTable.getColumn("Delete").setCellRenderer(new my_package.ButtonRenderer("Delete"));
        
        productTable.getColumn("Update").setCellEditor(new my_package.ButtonEditor(productTable, "Update"));
        productTable.getColumn("Delete").setCellEditor(new my_package.ButtonEditor(productTable, "Delete"));

        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        lbl_profile_pic = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_SR = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(249, 231, 159));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Dashboard");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Products");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Staff Accounts");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Orders");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lbl_logout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_logout.setText("Logout");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, -1));

        lbl_profile_pic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_profile_pic.setText("Admin Profile");
        lbl_profile_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_profile_picMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_profile_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 130, 420));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Manage Products");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, -1));

        productTable.setBackground(new java.awt.Color(204, 204, 204));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        productTable.setRowHeight(40);
        jScrollPane1.setViewportView(productTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 620, 250));

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADMIN PANEL");
        jPanel4.add(jLabel9);

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 40));

        jButton1.setText("View Users");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 120, 40));

        jButton2.setText("View Orders");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 120, 40));

        jButton3.setText("Add Product");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, 40));

        btn_SR.setText("View Sales Report");
        btn_SR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SRActionPerformed(evt);
            }
        });
        jPanel3.add(btn_SR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 770, 400));

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RAY'S FAST FOOD");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 930, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        // 1. Confirmation Dialog
    int a = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
    
    if (a == JOptionPane.YES_OPTION) { // Mas safe gamiton ang YES_OPTION kaysa manual nga '0'
        // 2. Paghimo og instance sa Login frame
        // Siguraduha nga ang spelling ni-match sa imong Login file
        my_package.Login loginFrame = new my_package.Login(); 
        
        // 3. I-pakita ang login screen
        loginFrame.setVisible(true); 
        
        // 4. I-close ang karaan nga dashboard
        this.dispose(); 
    }
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void lbl_profile_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profile_picMouseClicked
    AdminProfile ap = new AdminProfile(this.loggedInUser); 
    ap.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_lbl_profile_picMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. I-open ang viewusers frame (siguroha nga naa na kay viewusers.java)
    viewusers vu = new viewusers(); 
    vu.setVisible(true);
    
    // 2. I-close ang karaan nga dashboard
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // I-open ang vieworders frame
    vieworders vo = new vieworders();
    vo.setVisible(true);
    this.dispose(); // I-close ang admin dashboard
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// Kinahanglan (this, true) tungod kay JDialog ang addproduct
    addproduct ap = new addproduct(this, true); 
    ap.setLocationRelativeTo(null); // Para ma-center ang window
    ap.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_SRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SRActionPerformed
  String dateInput = btn_SR.getText().trim(); 
    
    if (!dateInput.isEmpty() && !dateInput.equals("Enter Date (YYYY-MM-DD)")) {
        try {
            // Mao ni ang saktong pagtawag: (Parent, Modal, String)
            SREPORT sr = new SREPORT(this, true, dateInput); 
            sr.setLocationRelativeTo(null);
            sr.setVisible(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btn_SRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindash("admin").setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_profile_pic;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
