/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import Admin.adduser;
import javax.swing.table.TableModel;

/**
 *
 * @author pc
 */
public class viewusers extends javax.swing.JFrame {
    public void displayData() {
    try {
        // Siguruha nga husto ang ngalan sa imong database file
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:project.db");
        String sql = "SELECT u_id, full_name, email, u_type, u_status FROM sign_up";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();
        
        // Gamit ang DbUtils para automatic ma-fill ang jTable
        user_table.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Refresh Error: " + e.getMessage());
    }
}

    /**
     * Creates new form viewusers
     */
    public viewusers() {
        initComponents();
        txt_search.setText("Search...");
        txt_search.setForeground(new java.awt.Color(153, 153, 153));
        displayUser();
        
    }
    public void loadUsers() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:sqlite:project.db");

            String sql = "SELECT u_id, full_name, email, u_type, u_status FROM sign_up";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) user_table.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("u_id"),
                    rs.getString("full_name"),
                    rs.getString("email"),
                    rs.getString("u_type"),
                    rs.getString("u_status")
                });
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // I-paste kini sa sulod sa public class viewusers
public void displayUser() {
    my_config.config conf = new my_config.config(); // Tawgon imong config class
    
    // SQL query para sa imong sign_up table
    String sql = "SELECT u_id, full_name, email, u_type, u_status FROM sign_up"; 
    
    // I-load ang data sa imong table
    conf.displayData(sql, user_table); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 0, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("VIEW USERS");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 0, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("USERS");
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        user_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(user_table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 620, 210));

        txt_search.setForeground(new java.awt.Color(51, 51, 51));
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_searchFocusLost(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 150, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 60, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 640, 300));

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 680, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
    // 1. Paghimo og instance sa Admin Dashboard
    // Kinahanglan nimo i-pass ang 'loggedInUser' (o kung unsa man ang variable name sa user)
    // Kung wala kay variable para sa user sa 'viewusers' frame, gamita lang una ang "Admin" 
    admindash admin = new admindash("Admin"); 
    
    // 2. I-pakita ang dashboard
    admin.setVisible(true); 
    
    // 3. I-close ang kasamtangan nga frame
    this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
   String query = txt_search.getText();                
    
    // Kon walay gi-type o ang placeholder ra ang naa, ayaw i-filter
    if (query.equals("Search...") || query.isEmpty()) {
        user_table.setRowSorter(null); // Ipakita tanan
    } else {
        // Kon nag-type na ang user (nga itom ang color), i-filter na ang table
        DefaultTableModel model = (DefaultTableModel) user_table.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        user_table.setRowSorter(trs);                
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }

    }//GEN-LAST:event_txt_searchKeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void user_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tableMouseClicked
     int row = user_table.getSelectedRow();
    TableModel model = user_table.getModel();
    
    // Pag-abli sa adduser form
    adduser addForm = new adduser(new javax.swing.JFrame(), true);
    
    // I-pass ang ID para mahibal-an kinsa ang i-update o delete
    addForm.userID = model.getValueAt(row, 0).toString();
    
    // I-fill ang mga fields sa data gikan sa table
    addForm.txtFullName.setText(model.getValueAt(row, 1).toString());
    addForm.txtEmail.setText(model.getValueAt(row, 2).toString());
    addForm.cmbType.setSelectedItem(model.getValueAt(row, 3).toString());
    addForm.cmbStatus.setSelectedItem(model.getValueAt(row, 4).toString());
    
    addForm.setVisible(true);
    displayData();

    }//GEN-LAST:event_user_tableMouseClicked

    private void txt_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusGained
      if(txt_search.getText().equals("Search...")){
        txt_search.setText(""); // Ma-clear ang "Search..."
        txt_search.setForeground(new java.awt.Color(0,0,0)); // Mahimong itom
    }

    }//GEN-LAST:event_txt_searchFocusGained

    private void txt_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusLost
      if(txt_search.getText().isEmpty()){
        txt_search.setText("Search..."); // Mobalik ang "Search..."
        txt_search.setForeground(new java.awt.Color(153,153,153)); // Balik sa gray
    }
    }//GEN-LAST:event_txt_searchFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewusers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTable user_table;
    // End of variables declaration//GEN-END:variables
}
