/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author pc
 */
public class customerdash extends javax.swing.JFrame {

    /**
     * Creates new form customerdash
     */
    public customerdash() {
        initComponents();
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    jTable1.getColumnModel().getColumn(1).setCellRenderer(centerRenderer); // Para sa Qty
    jTable1.getColumnModel().getColumn(2).setCellRenderer(centerRenderer); // Para sa Price
    }
public void loadProducts() {
    try {
        // 1. Connection sa Database
        Connection conn = DriverManager.getConnection("jdbc:sqlite:project.db");
        String sql = "SELECT p_name, p_price, p_image FROM products";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        // Maghimo kita og array sa imong mga labels para sayon i-loop
        javax.swing.JLabel[] imgLabels = {lbl_img1, lbl_img2, lbl_img3, lbl_img4, lbl_img5, lbl_img6};
        javax.swing.JLabel[] nameLabels = {lbl_name1, lbl_name2, lbl_name3, lbl_name4, lbl_name5, lbl_name6};
        javax.swing.JLabel[] priceLabels = {lbl_price1, lbl_price2, lbl_price3, lbl_price4, lbl_price5, lbl_price6};

        int i = 0;
        while (rs.next() && i < imgLabels.length) {
            // Kuhaon ang data gikan sa DB
            String name = rs.getString("p_name");
            String price = rs.getString("p_price");
            String path = rs.getString("p_image"); // Ang address sa picture

            // I-set ang text
            nameLabels[i].setText(name);
            priceLabels[i].setText("₱ " + price);

            // I-load ug i-resize ang image
            if (path != null && !path.isEmpty()) {
                ImageIcon icon = new ImageIcon(path);
                Image img = icon.getImage().getScaledInstance(imgLabels[i].getWidth(), imgLabels[i].getHeight(), Image.SCALE_SMOOTH);
                imgLabels[i].setIcon(new ImageIcon(img));
            }
            i++;
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error loading products: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_name1 = new javax.swing.JLabel();
        lbl_img1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lbl_price1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_img2 = new javax.swing.JLabel();
        lbl_name2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lbl_price2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_img3 = new javax.swing.JLabel();
        lbl_name3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lbl_price3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_name4 = new javax.swing.JLabel();
        lbl_img4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        lbl_price4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_img5 = new javax.swing.JLabel();
        lbl_name5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        lbl_price5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbl_name6 = new javax.swing.JLabel();
        lbl_price6 = new javax.swing.JLabel();
        lbl_img6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RAY'S FAST FOOD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 11, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 38));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_name1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name1.setText("Cheeseburger");
        jPanel3.add(lbl_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 20));

        lbl_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cburger.png"))); // NOI18N
        jPanel3.add(lbl_img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add to Cart");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        lbl_price1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_price1.setText("₱ 75");
        jPanel3.add(lbl_price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 54, 30, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 120));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ccn.png"))); // NOI18N
        jPanel4.add(lbl_img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        lbl_name2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name2.setText("Chiken Nuggets");
        jPanel4.add(lbl_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 20));

        jButton3.setBackground(new java.awt.Color(255, 153, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add to Cart");
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));

        lbl_price2.setText("₱ 99");
        jPanel4.add(lbl_price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 120));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ccola.png"))); // NOI18N
        jPanel5.add(lbl_img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 50));

        lbl_name3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_name3.setText("Cola");
        jPanel5.add(lbl_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 30, 10));

        jButton4.setBackground(new java.awt.Color(255, 153, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add to Cart");
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));

        lbl_price3.setText("₱ 35");
        jPanel5.add(lbl_price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 64, 30, 10));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 120, 120));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_name4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_name4.setText("French Fries");
        jPanel6.add(lbl_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, -1));

        lbl_img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cfries.png"))); // NOI18N
        jPanel6.add(lbl_img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        jButton5.setBackground(new java.awt.Color(255, 153, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Add to Cart");
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));

        lbl_price4.setText("₱ 50");
        jPanel6.add(lbl_price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 20));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 120));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cfc.png"))); // NOI18N
        jPanel7.add(lbl_img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        lbl_name5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_name5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name5.setText("Fried Chiken");
        jPanel7.add(lbl_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 10));

        jButton6.setBackground(new java.awt.Color(255, 153, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Add to Cart");
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));

        lbl_price5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_price5.setText("₱ 109");
        jPanel7.add(lbl_price5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 30, 20));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 120, 120));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_name6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_name6.setText("Ice Cream Sundae");
        jPanel8.add(lbl_name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 20));

        lbl_price6.setText("₱ 55");
        jPanel8.add(lbl_price6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, 20));

        lbl_img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cics.png"))); // NOI18N
        jPanel8.add(lbl_img6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 80));

        jButton7.setBackground(new java.awt.Color(255, 153, 51));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Add to Cart");
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 120, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 410, 370));

        jTextField1.setBackground(new java.awt.Color(204, 0, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Burgers");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 40));

        jTextField2.setBackground(new java.awt.Color(204, 0, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Chiken");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 40));

        jTextField3.setBackground(new java.awt.Color(204, 0, 0));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Drinks");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 150, 130, 40));

        jTextField4.setBackground(new java.awt.Color(204, 0, 0));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Sides");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 40));

        jTextField5.setBackground(new java.awt.Color(204, 0, 0));
        jTextField5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Desserts");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, 40));

        jTextPane1.setBackground(new java.awt.Color(249, 231, 159));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 410));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Price", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(jTable1);

        jPanel10.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 250));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Checkout");
        jPanel9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 323, 110, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Order Summary");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 170, 370));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 650, 400));
        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 30, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerdash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerdash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerdash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerdash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerdash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JLabel lbl_img2;
    private javax.swing.JLabel lbl_img3;
    private javax.swing.JLabel lbl_img4;
    private javax.swing.JLabel lbl_img5;
    private javax.swing.JLabel lbl_img6;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_name2;
    private javax.swing.JLabel lbl_name3;
    private javax.swing.JLabel lbl_name4;
    private javax.swing.JLabel lbl_name5;
    private javax.swing.JLabel lbl_name6;
    private javax.swing.JLabel lbl_price1;
    private javax.swing.JLabel lbl_price2;
    private javax.swing.JLabel lbl_price3;
    private javax.swing.JLabel lbl_price4;
    private javax.swing.JLabel lbl_price5;
    private javax.swing.JLabel lbl_price6;
    // End of variables declaration//GEN-END:variables
}
