/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;
import Admin.admindash;
import Customer.customerdash;
import Staff.staffdash;

/**
 *
 * @author pc
 */
public class Login extends javax.swing.JFrame {

    public static boolean isLoggedIn = false;

    /**
     * Creates new form Login
     */
    public Login() {
    initComponents();
    jPasswordField1.setEchoChar('*');
    jLabelEye.setIcon(new javax.swing.ImageIcon(
    getClass().getResource("/Images/eye_close.png")));

   // Parehas nga padding (35 pixels) para tupong gihapon sa Login
    javax.swing.border.Border padding = javax.swing.BorderFactory.createEmptyBorder(0, 35, 0, 0);

    jTextField_User.setBorder(javax.swing.BorderFactory.createCompoundBorder(jTextField_User.getBorder(), padding));
    jPasswordField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(jPasswordField1.getBorder(), padding));

    // I-set ang default placeholder
    jTextField_User.setText("Username");
    jPasswordField1.setText("Password");

    jTextField_User.setForeground(new java.awt.Color(153, 153, 153));
    jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));

    // I-off ang mask para makita ang "Password" text sa sugod
    jPasswordField1.setEchoChar((char)0);
    
    this.setLocationRelativeTo(null);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_User = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelEye = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 73, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/burgersss.png"))); // NOI18N
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/drinkss.png"))); // NOI18N
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginfries_1.png"))); // NOI18N
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 0, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("LOG IN");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 60));

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 200, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fries4.png"))); // NOI18N
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 44));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/username.png"))); // NOI18N
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 10, 10));

        jTextField_User.setText("       Username");
        jTextField_User.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UserFocusLost(evt);
            }
        });
        panel1.add(jTextField_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 200, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pass.png"))); // NOI18N
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 10, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Don't have an account? Click Here to Sign Up");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 327, 210, -1));

        jLabelEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye_close.png"))); // NOI18N
        jLabelEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEyeMouseClicked(evt);
            }
        });
        panel1.add(jLabelEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, 10));

        jPasswordField1.setText("Password");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        panel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 200, 30));

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 397));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 380, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // 1. Get the data from your text fields
    String user = jTextField_User.getText().trim(); 
    String pass = String.valueOf(jPasswordField1.getPassword());

    // Validation para sa empty o placeholder inputs
    if (user.equals("Username") || pass.equals("Password") || user.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter your credentials!");
        return;
    }

    my_config.config conf = new my_config.config();

    // 2. Kani nga part ang gi-fix: Pagkuha sa role gamit ang imong bag-ong config method
    String role = conf.getUserRole(user, pass); 

    if (role != null) { 
        try {
            // --- GIDUGANG NGA LINYA: I-set ang login status sa true ---
            isLoggedIn = true; 
            // ---------------------------------------------------------

            // 1. Siguruha nga "login" ra ang table name, dili "login_logs"
            String sqlLog = "INSERT INTO login (full_name, login_time) VALUES (?, CURRENT_TIMESTAMP)";
            conf.recordSession(sqlLog, user); 
            
            javax.swing.JOptionPane.showMessageDialog(null, "Login Successful!");

            if (role.equalsIgnoreCase("Admin")) {
                // 2. Siguruha nga husto ang package name 'Admin'
                Admin.admindash adm = new Admin.admindash(user);
                adm.setVisible(true);
            } 
            else if (role.equalsIgnoreCase("Staff")) {
                // Siguruha nga ang package name sa staffdash husto (e.g., Staff.staffdash)
                Staff.staffdash stf = new Staff.staffdash(); 
                stf.setVisible(true);
            }
            else {
                new Customer.customerdash().setVisible(true);
            }
            this.dispose();

        } catch (Exception e) {
            // 3. USBA KINI: Para ipakita sa Java ang tinuod nga error gikan sa SQL
            System.out.println("Actual SQL Error: " + e.getMessage()); 
            e.printStackTrace(); 
        }
    } else {
        // Error message kung mali ang credentials o wala ma-set ang u_status isip 'Active'
        javax.swing.JOptionPane.showMessageDialog(null, "Invalid Credentials or Account Pending!");
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField_UserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UserFocusGained
        // TODO add your handling code here:
        if(jTextField_User.getText().trim().equals("Username")){
    jTextField_User.setText("");
    jTextField_User.setForeground(new java.awt.Color(0,0,0)); 
}
    }//GEN-LAST:event_jTextField_UserFocusGained

    private void jTextField_UserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UserFocusLost
        // TODO add your handling code here:
        if(jTextField_User.getText().trim().isEmpty()){
    jTextField_User.setText("Username");
    jTextField_User.setForeground(new java.awt.Color(153,153,153)); 
}
    }//GEN-LAST:event_jTextField_UserFocusLost

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        SignUp signupForm = new SignUp();
        signupForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField1.getPassword()).equals("Password")) {
    jPasswordField1.setText("");
    jPasswordField1.setForeground(java.awt.Color.BLACK);
    jPasswordField1.setEchoChar('*');
}

    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        if (jPasswordField1.getPassword().length == 0) {
        jPasswordField1.setText("Password");
        jPasswordField1.setForeground(new java.awt.Color(153,153,153));
        jPasswordField1.setEchoChar((char) 0); // Always 0 for the placeholder text
    
}

    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jLabelEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEyeMouseClicked
        // Check if the password is currently visible (EchoChar is 0)
if (jPasswordField1.getEchoChar() == (char)0) {
    // Hide it again
    jPasswordField1.setEchoChar('*');
    // Optional: Change the icon back to a "closed eye" if you have one
    // jLabel_Eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye_closed.png")));
} else {
    // Show the password
    jPasswordField1.setEchoChar((char)0);
    // Optional: Change the icon to an "open eye"
    // jLabel_Eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye_open.png")));
}
    }//GEN-LAST:event_jLabelEyeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEye;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_User;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
