/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

/**
 *
 * @author pc
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
    initComponents();

    // 35 pixels nga space para dili matabunan ang black emoji
    jTextField_FullName.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        jTextField_FullName.getBorder(), 
        javax.swing.BorderFactory.createEmptyBorder(0, 35, 0, 0)));

    jTextField_Email.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        jTextField_Email.getBorder(), 
        javax.swing.BorderFactory.createEmptyBorder(0, 35, 0, 0)));

    jPasswordField_Pass.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        jPasswordField_Pass.getBorder(), 
        javax.swing.BorderFactory.createEmptyBorder(0, 35, 0, 0)));
    
    // Default blurd/gray color
    jTextField_FullName.setForeground(new java.awt.Color(153, 153, 153));
    jTextField_Email.setForeground(new java.awt.Color(153, 153, 153));
    jPasswordField_Pass.setForeground(new java.awt.Color(153, 153, 153));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_FullName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField_Pass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/burgersss.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, 53));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/drinkss.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginfries.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 50, 50));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 50));

        jTextField5.setBackground(new java.awt.Color(204, 0, 0));
        jTextField5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("SIGN UP");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/username.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 10));

        jTextField_FullName.setText("       Full Name");
        jTextField_FullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_FullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_FullNameFocusLost(evt);
            }
        });
        jTextField_FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FullNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 190, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 10, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pass.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 10, -1));

        jPasswordField_Pass.setText("       Password");
        jPasswordField_Pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PassFocusLost(evt);
            }
        });
        jPanel1.add(jPasswordField_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fries4.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 40, 50));

        jTextField_Email.setText("       Email");
        jTextField_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusLost(evt);
            }
        });
        jPanel1.add(jTextField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("Already have an account? Click Here to Login");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 290, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SignUp signupForm = new SignUp();
        signupForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_FullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FullNameFocusGained
        // TODO add your handling code here:
    if(jTextField_FullName.getText().trim().equals("Full Name")){
    jTextField_FullName.setText("");
    jTextField_FullName.setForeground(new java.awt.Color(0,0,0)); 
}
        
    }//GEN-LAST:event_jTextField_FullNameFocusGained

    private void jTextField_FullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FullNameFocusLost
        // TODO add your handling code here:
        if(jTextField_FullName.getText().trim().isEmpty()){
    jTextField_FullName.setText("Full Name");
    jTextField_FullName.setForeground(new java.awt.Color(153,153,153)); 
}
    }//GEN-LAST:event_jTextField_FullNameFocusLost

    private void jPasswordField_PassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PassFocusGained
        // TODO add your handling code here:
        if(jPasswordField_Pass.getText().trim().equals("Password")){
    jPasswordField_Pass.setText("");
    jPasswordField_Pass.setForeground(new java.awt.Color(0,0,0));
}
    }//GEN-LAST:event_jPasswordField_PassFocusGained

    private void jPasswordField_PassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PassFocusLost
        // TODO add your handling code here:
        if(jPasswordField_Pass.getText().trim().isEmpty()){
    jPasswordField_Pass.setText("        Password");
    jPasswordField_Pass.setForeground(new java.awt.Color(153,153,153));
}
    }//GEN-LAST:event_jPasswordField_PassFocusLost

    private void jTextField_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusGained
        // TODO add your handling code here:
        if(jTextField_Email.getText().trim().equals("Email")){
    jTextField_Email.setText("");
    jTextField_Email.setForeground(new java.awt.Color(0,0,0)); 
}
    }//GEN-LAST:event_jTextField_EmailFocusGained

    private void jTextField_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusLost
        // TODO add your handling code here:
        if(jTextField_Email.getText().trim().isEmpty()){
    jTextField_Email.setText("Email");
    jTextField_Email.setForeground(new java.awt.Color(153,153,153)); 
}
    }//GEN-LAST:event_jTextField_EmailFocusLost

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Login loginForm = new Login();
        loginForm.setVisible(true);
        loginForm.pack();
        loginForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jTextField_FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FullNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_FullNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPasswordField_Pass;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FullName;
    // End of variables declaration//GEN-END:variables
}
