/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

/**
 *
 * @author pc
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
    initComponents();
    jLabelEye.setVisible(true);
    jLabelEye.setEnabled(true);
    jLabelEye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabelEye.getParent().setComponentZOrder(jLabelEye, 0);
// 1. Padding para magtupong ang tanang text sa luyo sa icon
    javax.swing.border.Border padding = javax.swing.BorderFactory.createEmptyBorder(0, 35, 0, 0);
    
    jTextField_FullName.setBorder(javax.swing.BorderFactory.createCompoundBorder(jTextField_FullName.getBorder(), padding));
    jTextField_Email.setBorder(javax.swing.BorderFactory.createCompoundBorder(jTextField_Email.getBorder(), padding));
    jPasswordField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(jPasswordField1.getBorder(), padding));

    // 2. I-set ang "Placeholder" text ug color
    jTextField_FullName.setText("Full Name");
    jTextField_Email.setText("Email");
    jPasswordField1.setText("Password");

    jTextField_FullName.setForeground(new java.awt.Color(153, 153, 153));
    jTextField_Email.setForeground(new java.awt.Color(153, 153, 153));
    jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));

    // 3. MAO NI ANG IMPORTANTE: I-off ang tuldok para makita ang "Password" nga word
    jPasswordField1.setEchoChar((char)0); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_SignUp = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_FullName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelEye = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/burgersss.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, 53));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/drinkss.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginfries.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 50, 50));

        btn_SignUp.setBackground(new java.awt.Color(204, 0, 0));
        btn_SignUp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_SignUp.setForeground(new java.awt.Color(255, 255, 255));
        btn_SignUp.setText("SIGN UP");
        btn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 50));

        jTextField5.setBackground(new java.awt.Color(204, 0, 0));
        jTextField5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("SIGN UP");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/username.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 10));

        jTextField_FullName.setText("       Full Name");
        jTextField_FullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_FullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_FullNameFocusLost(evt);
            }
        });
        jTextField_FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FullNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 190, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 10, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pass.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 10, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fries4.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 40, 50));

        jTextField_Email.setText("       Email");
        jTextField_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusLost(evt);
            }
        });
        jPanel1.add(jTextField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("Already have an account? Click Here to Login");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabelEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye_close.png"))); // NOI18N
        jLabelEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEyeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 10, 10));

        jPasswordField1.setText("Password");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 290, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpActionPerformed
        // TODO add your handling code here:
       
  // 1. Kuhaa ang data gikan sa text fields
String fullName = jTextField_FullName.getText().trim();
String email = jTextField_Email.getText().trim();
String password = String.valueOf(jPasswordField1.getPassword());

// 2. Validation Logic
if (fullName.equals("Full Name") || email.equals("Email") || 
    password.equals("Password") || fullName.isEmpty() || email.isEmpty()) {
    
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Please fill in all fields!", 
        "Validation Error", 
        javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    my_config.config conf = new my_config.config();
    
    // 3. KINI ANG SAKTONG PAAGI SA PAG-CHECK (Email lang ang i-pasa)
    // Ang imong config.java nagkinahanglan og 'email' string, dili ang tibuok query.
    if (conf.isEmailTaken(email)) { 
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Email is already registered!", 
            "Duplicate Email", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return; 
    }

    // 4. Hash the password
    String hashedPassword = conf.hashPassword(password);
    
    // 5. Match SQL columns (full_name, email, password)
    String sql = "INSERT INTO sign_up (full_name, email, password) VALUES (?, ?, ?)";
    
    // I-save ang record gamit ang imong addRecord method
    conf.addRecord(sql, fullName, email, hashedPassword);

    // 6. Success handling ug transition sa Login
    Login loginForm = new Login();
    loginForm.setVisible(true);
    loginForm.pack();
    loginForm.setLocationRelativeTo(null);
    this.dispose();
    
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, 
        "System Error: " + e.getMessage(), 
        "Error", 
        javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btn_SignUpActionPerformed

    private void jTextField_FullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FullNameFocusGained
        // TODO add your handling code here:
    if(jTextField_FullName.getText().trim().equals("Full Name")){
    jTextField_FullName.setText("");
    jTextField_FullName.setForeground(new java.awt.Color(0,0,0)); 
}
        
    }//GEN-LAST:event_jTextField_FullNameFocusGained

    private void jTextField_FullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FullNameFocusLost
        // TODO add your handling code here:
        if(jTextField_FullName.getText().trim().isEmpty()){
    jTextField_FullName.setText("Full Name");
    jTextField_FullName.setForeground(new java.awt.Color(153,153,153)); 
}
    }//GEN-LAST:event_jTextField_FullNameFocusLost

    private void jTextField_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusGained
        // TODO add your handling code here:
        if(jTextField_Email.getText().trim().equals("Email")){
    jTextField_Email.setText("");
    jTextField_Email.setForeground(new java.awt.Color(0,0,0)); 
}
    }//GEN-LAST:event_jTextField_EmailFocusGained

    private void jTextField_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusLost
        // TODO add your handling code here:
        if(jTextField_Email.getText().trim().isEmpty()){
    jTextField_Email.setText("Email");
    jTextField_Email.setForeground(new java.awt.Color(153,153,153)); 
}
    }//GEN-LAST:event_jTextField_EmailFocusLost

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Login loginForm = new Login();
        loginForm.setVisible(true);
        loginForm.pack();
        loginForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jTextField_FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FullNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_FullNameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField1.getPassword()).equals("Password")) {
        jPasswordField1.setText("");
        jPasswordField1.setForeground(java.awt.Color.BLACK);
        jPasswordField1.setEchoChar('*');
    }

       
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
       if (String.valueOf(jPasswordField1.getPassword()).equals("Password")) {
    jPasswordField1.setText("");
    jPasswordField1.setEchoChar('*'); // Magsugod na ang masking
    jPasswordField1.setForeground(java.awt.Color.BLACK);

    
    }
           
        
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField1.getPassword()).isEmpty()) {
    jPasswordField1.setText("Password");
    jPasswordField1.setEchoChar((char)0); // I-pakita ang pulong nga "Password"
    jPasswordField1.setForeground(new java.awt.Color(153,153,153));

}
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jLabelEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEyeMouseClicked
        // Check kung ang text kay placeholder ba
String currentPass = String.valueOf(jPasswordField1.getPassword());

if (!currentPass.equals("Password")) {
    if (jPasswordField1.getEchoChar() == (char)0) {
        // I-hide pag-usab
        jPasswordField1.setEchoChar('*');
    } else {
        // I-pakita ang password
        jPasswordField1.setEchoChar((char)0);
    }
}
    }//GEN-LAST:event_jLabelEyeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEye;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FullName;
    // End of variables declaration//GEN-END:variables
}
